#!/usr/bin/env bash
# shellcheck disable=SC2034
#
# Shared helpers for Valet → MageBox migration scripts.
# Part of MageBox — https://github.com/qoliber/magebox
#
# This file is sourced by valet-to-magebox.sh and setup.sh.
# It must not be executed directly.

set -euo pipefail

readonly VALET_TO_MAGEBOX_CONFIG="${VALET_TO_MAGEBOX_CONFIG:-${HOME}/.config/magebox/valet-to-magebox.env}"
readonly VALET_TO_MAGEBOX_BIN_NAME="valet-to-magebox"
readonly VALET_TO_MAGEBOX_BIN="${HOME}/bin/${VALET_TO_MAGEBOX_BIN_NAME}"
export VALET_TM_DRY_RUN="${VALET_TM_DRY_RUN:-0}"

# --- Utilities ---

valet_tm_die() {
    printf 'Error: %s\n' "$*" >&2
    exit 1
}

valet_tm_shell_quote() {
    local value="$1"
    printf "'%s'" "${value//\'/\'\\\'\'}"
}

# --- Config file management ---

valet_tm_load_config() {
    if [[ -f "${VALET_TO_MAGEBOX_CONFIG}" ]]; then
        # shellcheck disable=SC1090
        source "${VALET_TO_MAGEBOX_CONFIG}"
    fi
}

valet_tm_save_config() {
    local brew_user="$1"
    local brew_pass="$2"
    local brew_port="${3:-3307}"
    local mb_host="${4:-127.0.0.1}"
    local mb_port="${5:-33080}"
    local mb_user="${6:-root}"
    local mb_pass="${7:-magebox}"

    mkdir -p "$(dirname "${VALET_TO_MAGEBOX_CONFIG}")"
    cat >"${VALET_TO_MAGEBOX_CONFIG}" <<EOF
# Generated by scripts/valet/setup.sh — do not commit.
BREW_MYSQL_PORT=${brew_port}
BREW_MYSQL_USER=$(valet_tm_shell_quote "${brew_user}")
BREW_MYSQL_PASSWORD=$(valet_tm_shell_quote "${brew_pass}")
MAGEBOX_MYSQL_HOST=$(valet_tm_shell_quote "${mb_host}")
MAGEBOX_MYSQL_PORT=${mb_port}
MAGEBOX_MYSQL_USER=$(valet_tm_shell_quote "${mb_user}")
MAGEBOX_MYSQL_PASSWORD=$(valet_tm_shell_quote "${mb_pass}")
EOF
    chmod 600 "${VALET_TO_MAGEBOX_CONFIG}"
}

# --- Interactive prompts ---

valet_tm_prompt_credentials() {
    local brew_user brew_pass brew_port
    local mb_host mb_port mb_user mb_pass

    echo "Homebrew MySQL (source — usually port 3307 while MageBox uses 3306/33080)"
    printf "  Port [%s]: " "${BREW_MYSQL_PORT:-3307}"
    read -r brew_port
    brew_port="${brew_port:-${BREW_MYSQL_PORT:-3307}}"

    printf "  Username [%s]: " "${BREW_MYSQL_USER:-root}"
    read -r brew_user
    brew_user="${brew_user:-${BREW_MYSQL_USER:-root}}"

    printf "  Password (leave empty if none): "
    read -rs brew_pass
    echo ""
    brew_pass="${brew_pass:-${BREW_MYSQL_PASSWORD:-}}"

    echo ""
    echo "MageBox MySQL (Docker — default port 33080)"
    printf "  Host [%s]: " "${MAGEBOX_MYSQL_HOST:-127.0.0.1}"
    read -r mb_host
    mb_host="${mb_host:-${MAGEBOX_MYSQL_HOST:-127.0.0.1}}"

    printf "  Port [%s]: " "${MAGEBOX_MYSQL_PORT:-33080}"
    read -r mb_port
    mb_port="${mb_port:-${MAGEBOX_MYSQL_PORT:-33080}}"

    printf "  Username [%s]: " "${MAGEBOX_MYSQL_USER:-root}"
    read -r mb_user
    mb_user="${mb_user:-${MAGEBOX_MYSQL_USER:-root}}"

    printf "  Password [%s]: " "${MAGEBOX_MYSQL_PASSWORD:-magebox}"
    read -rs mb_pass
    echo ""
    mb_pass="${mb_pass:-${MAGEBOX_MYSQL_PASSWORD:-magebox}}"

    valet_tm_save_config "${brew_user}" "${brew_pass}" "${brew_port}" \
        "${mb_host}" "${mb_port}" "${mb_user}" "${mb_pass}"
    echo ""
    echo "Saved credentials to ${VALET_TO_MAGEBOX_CONFIG}"
}

# --- Project discovery ---

valet_tm_magebox_db_host() {
    valet_tm_load_config
    printf '%s:%s' "${MAGEBOX_MYSQL_HOST:-127.0.0.1}" "${MAGEBOX_MYSQL_PORT:-33080}"
}

# Print unique project root paths (one per line): Valet Sites links + one level under parked paths.
# Override with VALET_TM_PROJECT_ROOTS (newline-separated) for testing.
valet_tm_discover_project_roots() {
    local -a seen=()
    local path link target child

    add_root() {
        local candidate="$1"
        [[ -d "${candidate}" ]] || return 0
        candidate="$(cd "${candidate}" && pwd -P)" || return 0
        if [[ ${#seen[@]} -gt 0 ]]; then
            local existing
            for existing in "${seen[@]}"; do
                [[ "${existing}" == "${candidate}" ]] && return 0
            done
        fi
        seen+=("${candidate}")
        printf '%s\n' "${candidate}"
    }

    if [[ -n "${VALET_TM_PROJECT_ROOTS:-}" ]]; then
        while IFS= read -r path; do
            [[ -n "${path}" ]] && add_root "${path}"
        done <<< "${VALET_TM_PROJECT_ROOTS}"
        return 0
    fi

    local sites_dir="${HOME}/.config/valet/Sites"
    if [[ -d "${sites_dir}" ]]; then
        for link in "${sites_dir}"/*; do
            [[ -e "${link}" ]] || continue
            if [[ -L "${link}" ]]; then
                target="$(cd "$(dirname "${link}")" && cd "$(readlink "${link}")" 2>/dev/null && pwd -P)" || continue
                add_root "${target}"
            elif [[ -d "${link}" ]]; then
                add_root "${link}"
            fi
        done
    fi

    local config="${HOME}/.config/valet/config.json"
    if [[ -f "${config}" ]]; then
        local park_path
        if command -v jq >/dev/null 2>&1; then
            while IFS= read -r park_path; do
                [[ -d "${park_path}" ]] || continue
                for child in "${park_path}"/*; do
                    [[ -d "${child}" ]] || continue
                    add_root "${child}"
                done
            done < <(jq -r '.paths[]?' "${config}" 2>/dev/null)
        elif command -v python3 >/dev/null 2>&1; then
            while IFS= read -r park_path; do
                [[ -d "${park_path}" ]] || continue
                for child in "${park_path}"/*; do
                    [[ -d "${child}" ]] || continue
                    add_root "${child}"
                done
            done < <(python3 -c 'import json,sys;p=json.load(open(sys.argv[1]));print("\n".join(p.get("paths",[])))' "${config}" 2>/dev/null)
        fi
    fi

    if command -v valet >/dev/null 2>&1; then
        while IFS= read -r path; do
            [[ -d "${path}" ]] || continue
            for child in "${path}"/*; do
                [[ -d "${child}" ]] || continue
                add_root "${child}"
            done
        done < <(valet paths 2>/dev/null || true)
    fi
}

# --- Project type detection ---

valet_tm_detect_project_type() {
    local root="$1"
    if [[ -f "${root}/bin/magento" && -f "${root}/app/etc/env.php" ]]; then
        echo "magento"
    elif [[ -f "${root}/artisan" && -f "${root}/.env" ]]; then
        echo "laravel"
    elif [[ -f "${root}/wp-config.php" ]]; then
        echo "wordpress"
    fi
}

# --- URL helpers ---

# Valet site folder name (Sites symlink) or project directory basename.
valet_tm_valet_site_name() {
    local root="$1"
    local link target name
    root="$(cd "${root}" && pwd -P)"
    local sites_dir="${HOME}/.config/valet/Sites"

    if [[ -d "${sites_dir}" ]]; then
        for link in "${sites_dir}"/*; do
            [[ -L "${link}" ]] || continue
            target="$(cd "$(dirname "${link}")" && cd "$(readlink "${link}")" 2>/dev/null && pwd -P)" || continue
            if [[ "${target}" == "${root}" ]]; then
                name="$(basename "${link}")"
                printf '%s' "${name}"
                return 0
            fi
        done
    fi

    basename "${root}"
}

# https://host/ with trailing slash (Magento-style).
valet_tm_project_base_url() {
    local root="$1"
    local host="" magebox_yaml="${root}/.magebox.yaml"

    if [[ -f "${magebox_yaml}" ]]; then
        host="$(grep -E '^[[:space:]]*-[[:space:]]*host:[[:space:]]*' "${magebox_yaml}" 2>/dev/null \
            | head -1 | sed -E 's/^[[:space:]]*-[[:space:]]*host:[[:space:]]*//' | tr -d "\"'")"
        if [[ -z "${host}" ]]; then
            host="$(grep -E '^[[:space:]]*host:[[:space:]]*' "${magebox_yaml}" 2>/dev/null \
                | head -1 | sed -E 's/^[[:space:]]*host:[[:space:]]*//' | tr -d "\"'")"
        fi
    fi

    if [[ -z "${host}" ]]; then
        host="$(valet_tm_valet_site_name "${root}").test"
    fi

    valet_tm_secure_url "https://${host}/" "trailing_slash"
}

# https://host without trailing slash (Laravel / WordPress).
valet_tm_project_app_url() {
    local url
    url="$(valet_tm_project_base_url "$1")"
    printf '%s' "${url%/}"
}

# Upgrade http→https; optional trailing slash for Magento base URLs.
valet_tm_secure_url() {
    local input="$1"
    local mode="${2:-no_trailing_slash}"

    [[ -n "${input}" ]] || return 0

    if command -v python3 >/dev/null 2>&1; then
        python3 - "${input}" "${mode}" <<'PY'
import sys
from urllib.parse import urlparse, urlunparse

raw = sys.argv[1].strip()
mode = sys.argv[2]
if not raw:
    sys.exit(0)
if "://" not in raw:
    raw = "https://" + raw.lstrip("/")
parsed = urlparse(raw)
host = parsed.netloc or parsed.path.split("/")[0]
path = parsed.path if parsed.netloc else "/" + "/".join(parsed.path.split("/")[1:])
if mode == "trailing_slash":
    if not path.endswith("/"):
        path = path.rstrip("/") + "/"
    if path == "":
        path = "/"
else:
    path = path.rstrip("/") or ""
out = urlunparse(("https", host, path or ("/" if mode == "trailing_slash" else ""), "", "", ""))
if mode != "trailing_slash" and out.endswith("/") and path == "":
    out = out.rstrip("/")
print(out)
PY
        return 0
    fi

    local url="${input}"
    url="${url/http:\/\//https://}"
    [[ "${url}" == https://* ]] || url="https://${url}"
    if [[ "${mode}" == "trailing_slash" ]]; then
        [[ "${url}" == */ ]] || url="${url}/"
    else
        url="${url%/}"
    fi
    printf '%s' "${url}"
}
