package project

import (
	"crypto/rand"
	"encoding/hex"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/qoliber/magebox/internal/config"
)

// envGenerator generates Magento 2 app/etc/env.php configuration
type envGenerator struct {
	projectPath string
	config      *config.Config
}

// newEnvGenerator creates a new env.php generator
func newEnvGenerator(projectPath string, cfg *config.Config) *envGenerator {
	return &envGenerator{
		projectPath: projectPath,
		config:      cfg,
	}
}

// Generate creates the env.php file
func (g *envGenerator) Generate() error {
	envPath := filepath.Join(g.projectPath, "app", "etc", "env.php")

	// Generate random prefix for Redis cache (3 chars + underscore)
	idPrefix := g.generateRandomPrefix(3) + "_"

	// Build the env.php content
	content := g.buildEnvPHP(idPrefix)

	// Ensure directory exists
	if err := os.MkdirAll(filepath.Dir(envPath), 0755); err != nil {
		return fmt.Errorf("failed to create app/etc directory: %w", err)
	}

	// Write the file
	if err := os.WriteFile(envPath, []byte(content), 0644); err != nil {
		return fmt.Errorf("failed to write env.php: %w", err)
	}

	return nil
}

// generateRandomPrefix generates a random alphanumeric prefix
func (g *envGenerator) generateRandomPrefix(length int) string {
	bytes := make([]byte, length)
	if _, err := rand.Read(bytes); err != nil {
		return "mb"
	}
	return hex.EncodeToString(bytes)[:length]
}

// generateCryptKey generates a random 32-char hex crypt key
func (g *envGenerator) generateCryptKey() string {
	bytes := make([]byte, 16)
	if _, err := rand.Read(bytes); err != nil {
		return "0000000000000000000000000000000000000000"
	}
	return hex.EncodeToString(bytes)
}

// buildEnvPHP builds the complete env.php content
func (g *envGenerator) buildEnvPHP(idPrefix string) string {
	var sb strings.Builder

	sb.WriteString("<?php\nreturn [\n")

	// Backend
	sb.WriteString("    'backend' => [\n")
	sb.WriteString("        'frontName' => 'admin'\n")
	sb.WriteString("    ],\n")

	// Crypt key
	sb.WriteString("    'crypt' => [\n")
	sb.WriteString(fmt.Sprintf("        'key' => '%s'\n", g.generateCryptKey()))
	sb.WriteString("    ],\n")

	// Session config
	g.buildSessionConfig(&sb, idPrefix)

	// Database config
	g.buildDatabaseConfig(&sb)

	// Resource
	sb.WriteString("    'resource' => [\n")
	sb.WriteString("        'default_setup' => [\n")
	sb.WriteString("            'connection' => 'default'\n")
	sb.WriteString("        ]\n")
	sb.WriteString("    ],\n")

	// X-Frame-Options
	sb.WriteString("    'x-frame-options' => 'SAMEORIGIN',\n")

	// MAGE_MODE
	mageMode := "developer"
	if g.config.Env != nil {
		if mode, ok := g.config.Env["MAGE_MODE"]; ok {
			mageMode = mode
		}
	}
	sb.WriteString(fmt.Sprintf("    'MAGE_MODE' => '%s',\n", mageMode))

	// Cache types
	g.buildCacheTypes(&sb)

	// Install date
	sb.WriteString("    'install' => [\n")
	sb.WriteString("        'date' => 'Generated by MageBox'\n")
	sb.WriteString("    ],\n")

	// Document root
	sb.WriteString("    'document_root_is_pub' => true,\n")

	// HTTP cache hosts (Varnish) - only if enabled
	if g.config.Services.HasVarnish() {
		g.buildVarnishConfig(&sb)
	}

	// Cache config (Redis or file)
	g.buildCacheConfig(&sb, idPrefix)

	// Lock provider
	sb.WriteString("    'lock' => [\n")
	sb.WriteString("        'provider' => 'db',\n")
	sb.WriteString("        'config' => [\n")
	sb.WriteString("            'prefix' => null\n")
	sb.WriteString("        ]\n")
	sb.WriteString("    ]\n")

	sb.WriteString("];\n")

	return sb.String()
}

// buildSessionConfig builds session configuration
func (g *envGenerator) buildSessionConfig(sb *strings.Builder, idPrefix string) {
	sb.WriteString("    'session' => [\n")

	if g.config.Services.HasRedis() {
		sb.WriteString("        'save' => 'redis',\n")
		sb.WriteString("        'redis' => [\n")
		sb.WriteString("            'host' => '127.0.0.1',\n")
		sb.WriteString("            'port' => '6379',\n")
		sb.WriteString("            'password' => '',\n")
		sb.WriteString("            'timeout' => '2.5',\n")
		sb.WriteString("            'persistent_identifier' => '',\n")
		sb.WriteString("            'database' => '2',\n")
		sb.WriteString("            'compression_threshold' => '2048',\n")
		sb.WriteString("            'compression_library' => 'gzip',\n")
		sb.WriteString("            'log_level' => '4',\n")
		sb.WriteString("            'max_concurrency' => '24',\n")
		sb.WriteString("            'break_after_frontend' => '5',\n")
		sb.WriteString("            'break_after_adminhtml' => '30',\n")
		sb.WriteString("            'first_lifetime' => '600',\n")
		sb.WriteString("            'bot_first_lifetime' => '60',\n")
		sb.WriteString("            'bot_lifetime' => '7200',\n")
		sb.WriteString("            'disable_locking' => '1',\n")
		sb.WriteString("            'min_lifetime' => '60',\n")
		sb.WriteString("            'max_lifetime' => '2592000'\n")
		sb.WriteString("        ]\n")
	} else {
		sb.WriteString("        'save' => 'files'\n")
	}

	sb.WriteString("    ],\n")
}

// buildDatabaseConfig builds database configuration
func (g *envGenerator) buildDatabaseConfig(sb *strings.Builder) {
	sb.WriteString("    'db' => [\n")
	sb.WriteString("        'table_prefix' => '',\n")
	sb.WriteString("        'connection' => [\n")
	sb.WriteString("            'default' => [\n")

	// Determine host and port based on MySQL/MariaDB version
	dbHost := "127.0.0.1"
	dbPort := "33080" // Default MySQL 8.0 port

	if g.config.Services.HasMySQL() {
		version := g.config.Services.MySQL.Version
		// Map version to port: 8.0 -> 33080, 8.4 -> 33084
		versionNoDots := strings.ReplaceAll(version, ".", "")
		if len(versionNoDots) >= 2 {
			dbPort = fmt.Sprintf("330%s", versionNoDots[:2])
		}
	} else if g.config.Services.HasMariaDB() {
		version := g.config.Services.MariaDB.Version
		versionNoDots := strings.ReplaceAll(version, ".", "")
		// MariaDB ports: 10.6 -> 33106, 11.4 -> 33114
		if len(versionNoDots) >= 2 {
			dbPort = fmt.Sprintf("331%s", versionNoDots[:2])
		}
	}

	sb.WriteString(fmt.Sprintf("                'host' => '%s:%s',\n", dbHost, dbPort))
	sb.WriteString(fmt.Sprintf("                'dbname' => '%s',\n", g.config.Name))
	sb.WriteString("                'username' => 'root',\n")
	sb.WriteString("                'password' => 'magebox',\n")
	sb.WriteString("                'model' => 'mysql4',\n")
	sb.WriteString("                'engine' => 'innodb',\n")
	sb.WriteString("                'initStatements' => 'SET NAMES utf8;',\n")
	sb.WriteString("                'active' => '1',\n")
	sb.WriteString("                'driver_options' => [\n")
	sb.WriteString("                    1014 => false\n")
	sb.WriteString("                ]\n")
	sb.WriteString("            ]\n")
	sb.WriteString("        ]\n")
	sb.WriteString("    ],\n")
}

// buildCacheTypes builds cache types configuration
func (g *envGenerator) buildCacheTypes(sb *strings.Builder) {
	sb.WriteString("    'cache_types' => [\n")
	sb.WriteString("        'config' => 1,\n")
	sb.WriteString("        'layout' => 1,\n")
	sb.WriteString("        'block_html' => 1,\n")
	sb.WriteString("        'collections' => 1,\n")
	sb.WriteString("        'reflection' => 1,\n")
	sb.WriteString("        'db_ddl' => 1,\n")
	sb.WriteString("        'eav' => 1,\n")
	sb.WriteString("        'customer_notification' => 1,\n")
	sb.WriteString("        'full_page' => 1,\n")
	sb.WriteString("        'config_integration' => 1,\n")
	sb.WriteString("        'config_integration_api' => 1,\n")
	sb.WriteString("        'translate' => 1,\n")
	sb.WriteString("        'config_webservice' => 1,\n")
	sb.WriteString("        'compiled_config' => 1\n")
	sb.WriteString("    ],\n")
}

// buildVarnishConfig builds Varnish http_cache_hosts configuration
func (g *envGenerator) buildVarnishConfig(sb *strings.Builder) {
	sb.WriteString("    'http_cache_hosts' => [\n")
	sb.WriteString("        [\n")
	sb.WriteString("            'host' => '127.0.0.1',\n")
	sb.WriteString("            'port' => '6081'\n")
	sb.WriteString("        ]\n")
	sb.WriteString("    ],\n")
}

// buildCacheConfig builds cache frontend configuration
func (g *envGenerator) buildCacheConfig(sb *strings.Builder, idPrefix string) {
	sb.WriteString("    'cache' => [\n")
	sb.WriteString("        'frontend' => [\n")

	if g.config.Services.HasRedis() {
		// Redis cache backend
		sb.WriteString("            'default' => [\n")
		sb.WriteString(fmt.Sprintf("                'id_prefix' => '%s',\n", idPrefix))
		sb.WriteString("                'backend' => 'Magento\\\\Framework\\\\Cache\\\\Backend\\\\Redis',\n")
		sb.WriteString("                'backend_options' => [\n")
		sb.WriteString("                    'server' => '127.0.0.1',\n")
		sb.WriteString("                    'database' => '0',\n")
		sb.WriteString("                    'port' => '6379',\n")
		sb.WriteString("                    'password' => '',\n")
		sb.WriteString("                    'compress_data' => '1',\n")
		sb.WriteString("                    'compression_lib' => ''\n")
		sb.WriteString("                ]\n")
		sb.WriteString("            ],\n")
		sb.WriteString("            'page_cache' => [\n")
		sb.WriteString(fmt.Sprintf("                'id_prefix' => '%s',\n", idPrefix))
		sb.WriteString("                'backend' => 'Magento\\\\Framework\\\\Cache\\\\Backend\\\\Redis',\n")
		sb.WriteString("                'backend_options' => [\n")
		sb.WriteString("                    'server' => '127.0.0.1',\n")
		sb.WriteString("                    'database' => '1',\n")
		sb.WriteString("                    'port' => '6379',\n")
		sb.WriteString("                    'password' => '',\n")
		sb.WriteString("                    'compress_data' => '1',\n")
		sb.WriteString("                    'compression_lib' => ''\n")
		sb.WriteString("                ]\n")
		sb.WriteString("            ]\n")
	} else {
		// File cache backend (default)
		sb.WriteString("            'default' => [\n")
		sb.WriteString(fmt.Sprintf("                'id_prefix' => '%s'\n", idPrefix))
		sb.WriteString("            ],\n")
		sb.WriteString("            'page_cache' => [\n")
		sb.WriteString(fmt.Sprintf("                'id_prefix' => '%s'\n", idPrefix))
		sb.WriteString("            ]\n")
	}

	sb.WriteString("        ],\n")
	sb.WriteString("        'allow_parallel_generation' => false\n")
	sb.WriteString("    ],\n")
}
