package installer

import (
	"fmt"
	"os"
	"os/exec"
	"os/user"
	"path/filepath"
	"strings"
)

// SudoersFile is where MageBox drops its passwordless-sudo rules.
const SudoersFile = "/etc/sudoers.d/magebox"

// sudoersMarker identifies files written by this generation of the generator.
// Older MageBox releases wrote wildcard rules such as "systemctl start php*-fpm",
// which sudo-rs (the default sudo on Ubuntu 26.04) refuses to parse — one such
// rule invalidates the whole file, so every MageBox rule stops working. The
// marker lets bootstrap recognize an outdated file and replace it.
const sudoersMarker = "# MageBox sudoers format: 2 (exact commands only)"

// serviceActions are the systemctl verbs MageBox issues while running.
var serviceActions = []string{"start", "stop", "reload", "restart"}

// FPMServiceNamer maps a PHP version such as "8.3" to its systemd unit name.
type FPMServiceNamer func(version string) string

// SudoersSpec describes the distribution-specific names behind the rules.
type SudoersSpec struct {
	// NginxBinary is the absolute path sudo resolves "nginx" to.
	NginxBinary string
	// PHPVersions are the versions MageBox may manage on this system.
	PHPVersions []string
	// FPMService names the PHP-FPM unit for a version.
	FPMService FPMServiceNamer
	// ExtraServices are additional units controlled without a password.
	ExtraServices []string
}

// UbuntuSudoersSpec describes Ubuntu and Debian, where units are php8.3-fpm.
func UbuntuSudoersSpec() SudoersSpec {
	return SudoersSpec{
		NginxBinary:   "/usr/sbin/nginx",
		PHPVersions:   PHPVersions,
		FPMService:    func(v string) string { return "php" + v + "-fpm" },
		ExtraServices: []string{"blackfire-agent"},
	}
}

// FedoraSudoersSpec describes Fedora and RHEL, where Remi units are php83-php-fpm.
func FedoraSudoersSpec() SudoersSpec {
	return SudoersSpec{
		NginxBinary:   "/usr/sbin/nginx",
		PHPVersions:   PHPVersions,
		FPMService:    func(v string) string { return "php" + strings.ReplaceAll(v, ".", "") + "-php-fpm" },
		ExtraServices: []string{"blackfire-agent"},
	}
}

// ArchSudoersSpec describes Arch, which ships a single php-fpm unit.
func ArchSudoersSpec() SudoersSpec {
	return SudoersSpec{
		NginxBinary:   "/usr/bin/nginx",
		PHPVersions:   PHPVersions,
		FPMService:    func(string) string { return "php-fpm" },
		ExtraServices: []string{"blackfire-agent"},
	}
}

// SudoersRules returns one rule per command MageBox runs unattended.
//
// Every rule names an exact command: sudo-rs rejects wildcards in arguments,
// and a bare command path (which would allow any argument) is a root
// escalation. Commands that only run during bootstrap or an explicit install
// are deliberately absent — asking for a password there is expected.
func SudoersRules(user string, spec SudoersSpec) []string {
	var commands []string

	for _, action := range serviceActions {
		commands = append(commands, "/usr/bin/systemctl "+action+" nginx")
	}
	commands = append(commands, spec.NginxBinary+" -s reload", spec.NginxBinary+" -t")

	seen := make(map[string]bool)
	for _, version := range spec.PHPVersions {
		unit := spec.FPMService(version)
		if seen[unit] {
			continue
		}
		seen[unit] = true
		for _, action := range serviceActions {
			commands = append(commands, "/usr/bin/systemctl "+action+" "+unit)
		}
	}

	for _, service := range spec.ExtraServices {
		for _, action := range append(serviceActions, "enable") {
			commands = append(commands, "/usr/bin/systemctl "+action+" "+service)
		}
	}

	rules := make([]string, 0, len(commands))
	for _, command := range commands {
		rules = append(rules, fmt.Sprintf("%s ALL=(ALL) NOPASSWD: %s", user, command))
	}
	return rules
}

// SudoersContent renders the file MageBox installs.
func SudoersContent(user string, spec SudoersSpec) string {
	var b strings.Builder
	b.WriteString("# MageBox - passwordless control of nginx and PHP-FPM for " + user + "\n")
	b.WriteString(sudoersMarker + "\n")
	b.WriteString("# Generated by 'magebox bootstrap' - do not edit manually\n\n")
	for _, rule := range SudoersRules(user, spec) {
		b.WriteString(rule + "\n")
	}
	return b.String()
}

// needsSudoersRewrite decides whether bootstrap has to write the file.
//
// The presence of a file proves nothing: every install upgraded from an older
// MageBox carries wildcard rules that sudo now rejects.
func needsSudoersRewrite(exists, valid, current bool) bool {
	return !exists || !valid || !current
}

// visudoBinary finds a syntax checker, preferring the one from the sudo
// package. Returns "" when none is installed.
func visudoBinary() string {
	for _, candidate := range []string{"/usr/sbin/visudo", "/usr/bin/visudo", "/usr/bin/visudo-rs"} {
		if _, err := os.Stat(candidate); err == nil {
			return candidate
		}
	}
	if path, err := exec.LookPath("visudo"); err == nil {
		return path
	}
	return ""
}

// validateSudoersContent checks content with visudo before it is installed, so
// a file the local sudo cannot parse never reaches /etc/sudoers.d.
//
// A missing visudo is not an error: the content is then installed unchecked,
// exactly as before.
func validateSudoersContent(content string) error {
	visudo := visudoBinary()
	if visudo == "" {
		return nil
	}

	dir, err := os.MkdirTemp("", "magebox-sudoers")
	if err != nil {
		return err
	}
	defer func() { _ = os.RemoveAll(dir) }()

	candidate := filepath.Join(dir, "magebox")
	if err := os.WriteFile(candidate, []byte(content), 0600); err != nil {
		return err
	}

	output, err := exec.Command(visudo, "-c", "-f", candidate).CombinedOutput()
	if err != nil {
		return fmt.Errorf("generated sudoers rules are invalid for this system's sudo: %w\n%s", err, strings.TrimSpace(string(output)))
	}
	return nil
}

// readInstalledSudoers returns the installed file's content. It needs sudo
// because the file is only readable by root.
func readInstalledSudoers() (string, bool) {
	output, err := exec.Command("sudo", "-n", "cat", SudoersFile).Output()
	if err != nil {
		return "", false
	}
	return string(output), true
}

// installedSudoersState reports whether the file exists, parses, and already
// holds the content MageBox wants.
func installedSudoersState(want string) (exists, valid, current bool) {
	if _, err := os.Stat(SudoersFile); err != nil {
		return false, false, false
	}
	exists = true

	got, readable := readInstalledSudoers()
	if !readable {
		// Cannot compare without a password prompt; rewriting is cheap and safe.
		return true, false, false
	}
	current = got == want

	if visudo := visudoBinary(); visudo != "" {
		valid = exec.Command("sudo", "-n", visudo, "-c", "-f", SudoersFile).Run() == nil
	} else {
		valid = true
	}
	return exists, valid, current
}

// sudoersUserFromEnv picks the invoking account out of the environment,
// returning "" when only root is named.
func sudoersUserFromEnv(lookup func(string) string) string {
	for _, key := range []string{"SUDO_USER", "USER", "LOGNAME"} {
		if value := lookup(key); value != "" && value != "root" {
			return value
		}
	}
	return ""
}

// sudoersUser returns the account the rules should grant to. Bootstrap is often
// started with sudo, where USER is root; SUDO_USER then names the human who
// invoked it, and rules for root would be pointless.
func sudoersUser() (string, error) {
	if account := sudoersUserFromEnv(os.Getenv); account != "" {
		return account, nil
	}
	if current, err := user.Current(); err == nil && current.Username != "" && current.Username != "root" {
		return current.Username, nil
	}
	return "", fmt.Errorf("could not determine which user to grant passwordless sudo to")
}

// ConfigureSudoersFor installs the rules for spec, replacing a file the local
// sudo cannot parse — which is every file written by MageBox before 2.1.1 on a
// system using sudo-rs.
func ConfigureSudoersFor(b *BaseInstaller, spec SudoersSpec) error {
	account, err := sudoersUser()
	if err != nil {
		return err
	}

	content := SudoersContent(account, spec)
	if err := validateSudoersContent(content); err != nil {
		return err
	}

	exists, valid, current := installedSudoersState(content)
	if !needsSudoersRewrite(exists, valid, current) {
		return nil
	}

	if err := b.WriteFile(SudoersFile, content); err != nil {
		return fmt.Errorf("failed to write sudoers file: %w", err)
	}
	if err := b.RunSudo("chmod", "0440", SudoersFile); err != nil {
		return fmt.Errorf("failed to set sudoers permissions: %w", err)
	}
	return nil
}
